#! /usr/bin/env python3

from table import Table
from player import Player
from move import move_manual, move_easyAI

player1 = Player(move_manual,'X')
playerAI = Player(move_easyAI,'O')

table = Table()
while True:
    table.turn(player1)
    table.turn(playerAI)
    if(table.checkWinner()):
        break

table.printWinner()
